const REQUIRED_VARS = [
 "PORT",
 "DB_USER",
 "DB_HOST",
 "DB_DATABASE",
 "DB_PASSWORD",
 "DB_PORT",
 "DISCORD_CLIENT_SECRET",
 "DISCORD_CLIENT_ID",
 "DISCORD_GUILD_ID",
 "DISCORD_BOT_TOKEN",
];
export default REQUIRED_VARS;
